### PR TITLE
Added commiter automation script

### PR DESCRIPTION
**Pull request by bwelboren**
Script that gets the commits by contributor of a repository.

### CODE REVIEW

**Review by ayham-1 — CHANGES_REQUESTED** [review]
Would like to have a number instead of list of commits.

**Comment by bwelboren** [comment]
> Would like to have a number instead of list of commits.

Should be done

**Comment by bwelboren** [comment]
Im still going to adjust the markdown because the style is failing

**Review by ayham-1 — APPROVED** [review]

**Comment by ayham-1** [comment]
Thanks for the help!

**Pull request merged**
