### PR TITLE
Add linearIntercept #20

### PR DESCRIPTION
**Pull request by ChaeDLR**
I think that's what you were asking for. If not i can change it.

### CODE REVIEW

**Review by ayham-1 — CHANGES_REQUESTED** [review]
We want to return the answer not print it to stdout :)

**Review by ayham-1 — CHANGES_REQUESTED** [review]
There is a seperate file called calcLinearIntercept where the class should be defined, my bad I didn't notice the edited files from the first review.

**Comment by ChaeDLR** [comment]
I think thats right.

**Comment by ayham-1** [comment]
Fixed and better documented at: #22
Thanks for the effort put on this!

**Pull request closed without merging**
